### ISSUE TITLE
Release 1.2

### ISSUE THREAD

**Issue by amoeba** [NCEAS/oboe#18]
[ECSO](https://github.com/DataONEorg/sem-prov-ontologies/tree/ECSO8-add_non-carbon_measurements/observation) imports OBOE v1.2 which hasn't been released but it looks like OBOE v1.2 is super close to being released looking at the commit history here.

Could we get a few folks, esp. @mbjones, @mpsaloha, @mobb, and @stevenchong to weigh in here on whether there are any outstanding tasks?

Otherwise, it looks like we just need to:

- [x] Issue a 1.2 DOI
- [x] Create a new Release here on GitHub
- [x] Update README and any other docs
- [ ] ~~Set up purl.dataone.org redirects~~
- [x] Set up on Bioportal

Anything else?

**Comment by mbjones** [comment]
LGTM.

**Comment by stevenchong** [comment]
I think the original plan was to create other object properties so we can annotate other parts of an EML document (e.g. entities) -- right now we can only annotate attributes with `containsMeasurementsOfType`. Perhaps we can hold off on those until a future release.

**Comment by mbjones** [comment]
@stevenchong If they are simple and non-controversial, I would argue its best to add them now and then release so we don't immediately have versioning issues.  Can you add a ticket describing the desired classes/properties and some examples of use?

**Comment by amoeba** [comment]
This is still a WIP but I just added another TODO item, "Set up on BioPortal". The URIs for terms in OBOE won't change but setting OBOE up on BioPortal will let us redirect users to a human-readable landing page for each term (we just show them the entire OWL file now, which is incomprehensible to some).

**Comment by stevenchong** [comment]
@mpsaloha had asked me to add labels to the object properties in the OBOE-Core OWL file. I have it ready to go

**Comment by amoeba** [comment]
Glad to hear it, @stevenchong 	.  Are there more ontology changes in order?

**Comment by stevenchong** [comment]
Not that I know of...

**Comment by amoeba** [comment]
Thanks!

**Comment by amoeba** [comment]
All done. I struck out purl.dataone.org redirects because I'm not sure what I meant there.
