### ISSUE TITLE
set up OBOE namespace redirects

### ISSUE THREAD

**Issue by mbjones** [NCEAS/oboe#6]
The current OBOE namespaces redirect to their corresponding OWL files that are stored on SVN.  Now that we've moved to git, we need to:
- [x] Redirect existing namespaces to their new Git locations
- [x] Add redirects for all OBOE 1.1 namespaces

**Comment by amoeba** [comment]
We've got a rewrite rule that handles this, if I understand your goal correctly.

```
RewriteRule /oboe/oboe.1.1/(.*) https://raw.githubusercontent.com/NCEAS/oboe/OBOE_1_1_BRANCH/$1 [P,L]
```

And I've tested it works nicely.

**Comment by amoeba** [comment]
PS, I updated the redirect to redirect to the 1.1 release as tagged here on GitHub.
