### ISSUE TITLE
update DOI for 1.1 release

### ISSUE THREAD

**Issue by mbjones** [NCEAS/oboe#7]
The DOI (doi:10.5063/F11C1TTM) for the 1.1 release was issued from the KNB, but needs to be updated to point to the proper distribution channels when the 1.1 release is cut.  In the meantime, point the DOI at Github.

**Comment by amoeba** [comment]
Just checking in on this. The DOI is pointed at https://github.com/NCEAS/oboe/tree/OBOE_1_1 at the moment. What is the proper distribution channel for this and where should it point?

**Comment by mbjones** [comment]
I've been in limbo on software releases with KNB DOIs.  Technically, we are responsible for the long-term archival of the DOI content, and so we should have a copy on the KNB.  However, as we don't currently really support a software metadata standard well (e.g., CodeMeta), I haven't wanted to archive it as just an EML doc.  So, I've been issuing the DOIs and pointing them at GitHub tags across all of our software packages.  We need a better solution, but if you want to continue that trend it could be cleaned up with the rest of them when we decide on an approach.

**Comment by amoeba** [comment]
I agree that having GitHub be our distribution channel isn't ideal but I think it is sufficient. Would a better solution look like hosting a main page (like https://semtools.ecoinformatics.org/oboe) with separate places to point each DOI for more information on each release? I see we essentially deprecated https://semtools.ecoinformatics.org/oboe in favor of this GitHub repo. 

I'm fine with keeping the DOI as-is (pointing at a GH tag) and looking to possibly change things up in the future. I'll close this and close out the 1.1 milestone but put a new issue in for a future milestone to take another look at our approach.

Thanks!
